version: '3'
services:
  app:
    image: gcr.io/digital-ucdavis-edu/simple-spa:main
    env_file:
      - .env
    ports:
      - ${APP_HOST_PORT:-3000}:${APP_CONTAINER_PORT:-3000}
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    command: node index.js
  db:
    image: postgres:15.3
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
